spring:
  application:
    name: student-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_center?useUnicode=true&characterEncoding=utf-8
    username: root
    password: MySQL@ZJ2
    database_name: student_center

server:
  port: 8080


